spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/worklog
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    filter:
      order: 10

app:
  jwt:
    secret: ${JWT_SECRET:your-256-bit-secret-key-here-minimum-32-characters}
    access-token-expiration: 86400000  # 24 hours in milliseconds
    refresh-token-expiration: 604800000 # 7 days in milliseconds

logging:
  level:
    org.springframework.security: DEBUG
    com.worklog: DEBUG 